version: '3'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      - REDIS_USER=
      - REDIS_PASSWORD=password
      - REDIS_ARGS=--requirepass password
